#ifndef __CARDPATCHES__
#define __CARDPATCHES__

#include "asm\__CARDSync.h"
#include "asm\CARDCheck.h"
#include "asm\CARDCheckAsync.h"
#include "asm\CARDCheckEX.h"
#include "asm\CARDClose.h"
#include "asm\CARDCreate.h"
#include "asm\CARDDelete.h"
#include "asm\CARDFastOpen.h"
#include "asm\CARDFreeBlocks.h"
#include "asm\CARDGetEncoding.h"
#include "asm\CARDGetMemSize.h"
#include "asm\CARDGetSerialNo.h"
#include "asm\CARDGetStats.h"
#include "asm\CARDMount.h"
#include "asm\CARDMountAsync.h"
#include "asm\CARDOpen.h"
#include "asm\CARDProbe.h"
#include "asm\CARDProbeEX.h"
#include "asm\CARDRead.h"
#include "asm\CARDSetStats.h"
#include "asm\CARDWrite.h"
#include "asm\CARDGetResultCode.h"
#include "asm\CARDGetXferredBytes.h"
#include "asm\CARDFastDelete.h"
#include "asm\CARDRename.h"

#endif
